import React, { useState, useRef, useCallback } from 'react'
import './NodePage.css'

// ── Step type definitions ─────────────────────────────────────────────────────
const STEP_TYPES = {
  shell: {
    label: 'Shell Command',
    icon: '⌨',
    color: '#4A6BC8',
    description: 'Run any command. Use {input} and {output} as placeholders.',
    fields: ['command'],
    defaultCommand: 'ffmpeg -y -i "{input}" "{output}"',
  },
  whisper: {
    label: 'Whisper Transcribe',
    icon: '🎙',
    color: '#8B35CC',
    description: 'Transcribe audio/video to SRT using Whisper.',
    fields: ['model', 'wordsPerLine', 'outputFormat'],
    defaultCommand: 'whisper "{input}" --model {model} --output_format {outputFormat} --word_timestamps True --max_words_per_line {wordsPerLine} --output_dir "{outputDir}"',
  },
  ai_analyse: {
    label: 'AI Analyse',
    icon: '🤖',
    color: '#6B1FA8',
    description: 'Send the input file content to the AI with a custom prompt. Output is saved as JSON or TXT.',
    fields: ['prompt', 'outputFormat'],
  },
  ffmpeg_clip: {
    label: 'Clip by Timestamps',
    icon: '✂',
    color: '#1B8FAD',
    description: 'Read timestamps from a JSON file and clip the original video into segments.',
    fields: ['sourceVideo'],
  },
  for_each_shell: {
    label: 'For Each — Shell',
    icon: '🔁',
    color: '#1B9FD4',
    description: 'Run a shell command once per clip generated by a previous step.',
    fields: ['command'],
    defaultCommand: 'ffmpeg -y -i "{input}" "{output}"',
  },
  scale_916: {
    label: 'Scale to 9:16',
    icon: '📱',
    color: '#27AE85',
    description: 'Scale and pad video to 1080×1920 for YouTube Shorts / TikTok / Reels.',
    fields: [],
    defaultCommand: 'ffmpeg -y -i "{input}" -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2:black" -c:v libx264 -crf 23 -c:a aac "{output}"',
  },
  burn_captions: {
    label: 'Burn Captions',
    icon: '💬',
    color: '#C8A020',
    description: 'Burn an SRT file into the video as hardcoded subtitles.',
    fields: ['fontsize', 'fontcolor'],
  },
}

// ── Built-in pipeline templates ───────────────────────────────────────────────
const TEMPLATES = [
  {
    id: 'yt-shorts',
    name: 'YouTube Shorts Generator',
    description: 'Transcribe → AI picks moments → clip → caption → 9:16',
    icon: '📱',
    steps: [
      { id: 1, type: 'whisper',       title: 'Transcribe video',          model: 'base', wordsPerLine: '2', outputFormat: 'srt' },
      { id: 2, type: 'ai_analyse',    title: 'AI picks best moments',     prompt: 'Read this SRT transcript and return a JSON array of the 3-5 best moments for YouTube Shorts. Each item must have: start (HH:MM:SS), end (HH:MM:SS), reason (string). Return ONLY valid JSON, no explanation.', outputFormat: 'json' },
      { id: 3, type: 'ffmpeg_clip',   title: 'Clip segments',             sourceVideo: '{original}' },
      { id: 4, type: 'whisper',       title: 'Caption each clip',         model: 'base', wordsPerLine: '2', outputFormat: 'srt' },
      { id: 5, type: 'burn_captions', title: 'Burn captions',             fontsize: '22', fontcolor: 'white' },
      { id: 6, type: 'scale_916',     title: 'Scale to 9:16',             },
    ],
  },
  {
    id: 'compress-batch',
    name: 'Batch Compress for Web',
    description: 'Compress multiple videos to H264 for web delivery',
    icon: '📦',
    steps: [
      { id: 1, type: 'shell', title: 'Compress H264', command: 'ffmpeg -y -i "{input}" -c:v libx264 -crf 28 -preset slow -c:a aac -b:a 128k "{output}"' },
    ],
  },
  {
    id: 'extract-audio',
    name: 'Extract + Transcribe Audio',
    description: 'Pull audio track then generate SRT transcript',
    icon: '🎵',
    steps: [
      { id: 1, type: 'shell',   title: 'Extract audio', command: 'ffmpeg -y -i "{input}" -vn -acodec mp3 -ab 192k "{output}.mp3"' },
      { id: 2, type: 'whisper', title: 'Transcribe',    model: 'base', wordsPerLine: '8', outputFormat: 'srt' },
    ],
  },
  {
    id: 'blank',
    name: 'Blank Pipeline',
    description: 'Start from scratch',
    icon: '＋',
    steps: [],
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────
function uid() { return Math.random().toString(36).slice(2, 9) }

function defaultStep(type) {
  const def = STEP_TYPES[type]
  return {
    id: uid(),
    type,
    title: def.label,
    command:      def.defaultCommand ?? '',
    model:        'base',
    wordsPerLine: '2',
    outputFormat: 'srt',
    prompt:       '',
    sourceVideo:  '{original}',
    fontsize:     '22',
    fontcolor:    'white',
  }
}

function stepColor(type) { return STEP_TYPES[type]?.color ?? '#888' }
function stepIcon(type)  { return STEP_TYPES[type]?.icon  ?? '⚙' }
function stepLabel(type) { return STEP_TYPES[type]?.label ?? type }

// ── Main Page ─────────────────────────────────────────────────────────────────
export default function NodePage({ project, settingsStore, onRunPipeline }) {
  const [pipelines, setPipelines]         = useState(() => loadPipelines())
  const [activePipelineId, setActive]     = useState(pipelines[0]?.id ?? null)
  const [selectedStepId, setSelectedStep] = useState(null)
  const [showTemplates, setShowTemplates] = useState(false)
  const [runState, setRunState]           = useState(null) // { status, stepId, log[] }
  const [inputFile, setInputFile]         = useState(null)
  const dragStep = useRef(null)
  const dragOver = useRef(null)

  const activePipeline = pipelines.find(p => p.id === activePipelineId)
  const selectedStep   = activePipeline?.steps.find(s => s.id === selectedStepId)

  // ── Persistence ───────────────────────────────────────────────────────────
  function loadPipelines() {
    try {
      const raw = localStorage.getItem('vizio_pipelines')
      return raw ? JSON.parse(raw) : []
    } catch { return [] }
  }

  function savePipelines(updated) {
    setPipelines(updated)
    try { localStorage.setItem('vizio_pipelines', JSON.stringify(updated)) } catch {}
  }

  // ── Pipeline CRUD ─────────────────────────────────────────────────────────
  function createFromTemplate(template) {
    const p = {
      id: uid(),
      name: template.id === 'blank' ? 'Untitled Pipeline' : template.name,
      description: template.description,
      steps: template.steps.map(s => ({ ...s, id: uid() })),
      createdAt: Date.now(),
    }
    savePipelines([...pipelines, p])
    setActive(p.id)
    setShowTemplates(false)
  }

  function deletePipeline(id) {
    const updated = pipelines.filter(p => p.id !== id)
    savePipelines(updated)
    setActive(updated[0]?.id ?? null)
  }

  function renamePipeline(id, name) {
    savePipelines(pipelines.map(p => p.id === id ? { ...p, name } : p))
  }

  function updatePipeline(updated) {
    savePipelines(pipelines.map(p => p.id === updated.id ? updated : p))
  }

  // ── Step CRUD ─────────────────────────────────────────────────────────────
  function addStep(type) {
    if (!activePipeline) return
    const step = defaultStep(type)
    updatePipeline({ ...activePipeline, steps: [...activePipeline.steps, step] })
    setSelectedStep(step.id)
  }

  function removeStep(stepId) {
    if (!activePipeline) return
    updatePipeline({ ...activePipeline, steps: activePipeline.steps.filter(s => s.id !== stepId) })
    if (selectedStepId === stepId) setSelectedStep(null)
  }

  function updateStep(stepId, patch) {
    if (!activePipeline) return
    updatePipeline({
      ...activePipeline,
      steps: activePipeline.steps.map(s => s.id === stepId ? { ...s, ...patch } : s),
    })
  }

  // ── Drag reorder ──────────────────────────────────────────────────────────
  function onDragStart(e, idx) { dragStep.current = idx }
  function onDragEnter(e, idx) { dragOver.current = idx }
  function onDragEnd() {
    if (!activePipeline) return
    const steps = [...activePipeline.steps]
    const from  = dragStep.current
    const to    = dragOver.current
    if (from === null || to === null || from === to) return
    const [moved] = steps.splice(from, 1)
    steps.splice(to, 0, moved)
    updatePipeline({ ...activePipeline, steps })
    dragStep.current = null
    dragOver.current = null
  }

  // ── Pick input file ───────────────────────────────────────────────────────
  async function pickInputFile() {
    const path = await window.electron?.project?.choosePath?.()
    if (path) setInputFile(path)
  }

  // ── Run pipeline ──────────────────────────────────────────────────────────
  async function runPipeline() {
    if (!activePipeline || !inputFile) return
    // Convert pipeline steps → workflow steps the existing engine understands
    const workflow = buildWorkflow(activePipeline, inputFile, project)
    setRunState({ status: 'running', stepId: null, log: [] })
    onRunPipeline?.(workflow)
  }

  // ── Export / Import ───────────────────────────────────────────────────────
  function exportPipeline() {
    if (!activePipeline) return
    const blob = new Blob([JSON.stringify(activePipeline, null, 2)], { type: 'application/json' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `${activePipeline.name.replace(/\s+/g, '_')}.pipeline.json`
    a.click()
  }

  function importPipeline(e) {
    const file = e.target.files[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = ev => {
      try {
        const p = JSON.parse(ev.target.result)
        p.id = uid()
        savePipelines([...pipelines, p])
        setActive(p.id)
      } catch { alert('Invalid pipeline file') }
    }
    reader.readAsText(file)
    e.target.value = ''
  }

  return (
    <div className="node-page">

      {/* ── Left: pipeline list ─────────────────────────────────────── */}
      <aside className="node-sidebar">
        <div className="node-sidebar-header">
          <span className="node-sidebar-title">Pipelines</span>
          <button className="node-new-btn" onClick={() => setShowTemplates(true)} title="New pipeline">＋</button>
        </div>

        <div className="node-pipeline-list">
          {pipelines.length === 0 && (
            <div className="node-empty-list">
              <div className="node-empty-icon">⬡</div>
              <div>No pipelines yet</div>
              <button className="node-create-first" onClick={() => setShowTemplates(true)}>
                Create one
              </button>
            </div>
          )}
          {pipelines.map(p => (
            <div
              key={p.id}
              className={`node-pipeline-row ${p.id === activePipelineId ? 'active' : ''}`}
              onClick={() => { setActive(p.id); setSelectedStep(null) }}
            >
              <div className="node-pipeline-row-info">
                <div className="node-pipeline-row-name">{p.name}</div>
                <div className="node-pipeline-row-meta">{p.steps.length} step{p.steps.length !== 1 ? 's' : ''}</div>
              </div>
              <button
                className="node-pipeline-delete"
                onClick={e => { e.stopPropagation(); deletePipeline(p.id) }}
                title="Delete"
              >×</button>
            </div>
          ))}
        </div>

        {/* Import */}
        <label className="node-import-btn" title="Import .pipeline.json">
          ↑ Import
          <input type="file" accept=".json" style={{ display:'none' }} onChange={importPipeline} />
        </label>
      </aside>

      {/* ── Center: pipeline canvas ─────────────────────────────────── */}
      <main className="node-canvas">
        {!activePipeline ? (
          <div className="node-canvas-empty">
            <div className="node-canvas-empty-icon">⬡</div>
            <div className="node-canvas-empty-title">No pipeline selected</div>
            <div className="node-canvas-empty-sub">Create one from the sidebar</div>
          </div>
        ) : (
          <>
            {/* Pipeline header */}
            <div className="node-canvas-header">
              <input
                className="node-pipeline-name-input"
                value={activePipeline.name}
                onChange={e => renamePipeline(activePipeline.id, e.target.value)}
              />
              <div className="node-canvas-header-actions">
                <button className="node-action-btn" onClick={exportPipeline} title="Export pipeline">↓ Export</button>
              </div>
            </div>

            {/* Input file row */}
            <div className="node-input-row">
              <div className="node-input-label">INPUT FILE</div>
              <button className="node-input-pick" onClick={pickInputFile}>
                {inputFile ? inputFile.split(/[\\/]/).pop() : 'Choose file…'}
              </button>
              {inputFile && (
                <button className="node-input-clear" onClick={() => setInputFile(null)}>×</button>
              )}
            </div>

            {/* Steps */}
            <div className="node-steps">
              {activePipeline.steps.length === 0 && (
                <div className="node-steps-empty">
                  Add steps from the panel on the right →
                </div>
              )}

              {activePipeline.steps.map((step, idx) => (
                <React.Fragment key={step.id}>
                  <div
                    className={`node-step ${selectedStepId === step.id ? 'selected' : ''}`}
                    onClick={() => setSelectedStep(step.id)}
                    draggable
                    onDragStart={e => onDragStart(e, idx)}
                    onDragEnter={e => onDragEnter(e, idx)}
                    onDragEnd={onDragEnd}
                    onDragOver={e => e.preventDefault()}
                  >
                    {/* Step number */}
                    <div className="node-step-num" style={{ background: stepColor(step.type) }}>
                      {idx + 1}
                    </div>

                    {/* Step body */}
                    <div className="node-step-body">
                      <div className="node-step-top">
                        <span className="node-step-icon">{stepIcon(step.type)}</span>
                        <span className="node-step-title">{step.title}</span>
                        <span className="node-step-type-badge" style={{ borderColor: stepColor(step.type), color: stepColor(step.type) }}>
                          {stepLabel(step.type)}
                        </span>
                      </div>

                      {/* Preview of key config */}
                      <div className="node-step-preview">
                        {step.type === 'shell' || step.type === 'for_each_shell' || step.type === 'scale_916' ? (
                          <code>{(step.command || STEP_TYPES[step.type]?.defaultCommand || '').slice(0, 80)}…</code>
                        ) : step.type === 'whisper' ? (
                          <span>model: {step.model} · {step.wordsPerLine} words/line · {step.outputFormat}</span>
                        ) : step.type === 'ai_analyse' ? (
                          <span className="node-step-prompt-preview">{(step.prompt || '').slice(0, 70)}…</span>
                        ) : step.type === 'ffmpeg_clip' ? (
                          <span>Clips from AI analysis JSON → individual segments</span>
                        ) : step.type === 'burn_captions' ? (
                          <span>fontsize: {step.fontsize} · color: {step.fontcolor}</span>
                        ) : null}
                      </div>
                    </div>

                    {/* Run status indicator */}
                    {runState?.stepId === step.id && (
                      <div className="node-step-running-dot" />
                    )}

                    {/* Remove */}
                    <button
                      className="node-step-remove"
                      onClick={e => { e.stopPropagation(); removeStep(step.id) }}
                      title="Remove step"
                    >×</button>
                  </div>

                  {/* Connector arrow between steps */}
                  {idx < activePipeline.steps.length - 1 && (
                    <div className="node-connector">
                      <div className="node-connector-line" style={{ background: stepColor(step.type) }} />
                      <div className="node-connector-arrow" style={{ borderTopColor: stepColor(activePipeline.steps[idx+1].type) }}>▼</div>
                      <div className="node-connector-label">
                        output → input
                      </div>
                    </div>
                  )}
                </React.Fragment>
              ))}
            </div>

            {/* Run bar */}
            <div className="node-run-bar">
              <div className="node-run-info">
                {inputFile
                  ? <span className="node-run-file">▶ {inputFile.split(/[\\/]/).pop()}</span>
                  : <span className="node-run-hint">Pick an input file to run</span>
                }
              </div>
              <button
                className={`node-run-btn ${!inputFile ? 'disabled' : ''}`}
                onClick={runPipeline}
                disabled={!inputFile || activePipeline.steps.length === 0}
              >
                Run Pipeline
              </button>
            </div>
          </>
        )}
      </main>

      {/* ── Right: step editor / add panel ─────────────────────────── */}
      <aside className="node-editor">
        {selectedStep ? (
          <StepEditor
            step={selectedStep}
            onUpdate={patch => updateStep(selectedStep.id, patch)}
            onClose={() => setSelectedStep(null)}
          />
        ) : (
          <AddStepPanel onAdd={addStep} />
        )}
      </aside>

      {/* ── Template picker modal ───────────────────────────────────── */}
      {showTemplates && (
        <TemplateModal
          onSelect={createFromTemplate}
          onClose={() => setShowTemplates(false)}
        />
      )}
    </div>
  )
}

// ── Step editor panel ─────────────────────────────────────────────────────────
function StepEditor({ step, onUpdate, onClose }) {
  const def = STEP_TYPES[step.type]

  return (
    <div className="node-step-editor">
      <div className="node-editor-header">
        <span className="node-editor-header-icon" style={{ color: stepColor(step.type) }}>
          {stepIcon(step.type)}
        </span>
        <span className="node-editor-header-title">Edit Step</span>
        <button className="node-editor-close" onClick={onClose}>←</button>
      </div>

      <div className="node-editor-body">
        <label className="node-field-label">Step title</label>
        <input
          className="node-field-input"
          value={step.title}
          onChange={e => onUpdate({ title: e.target.value })}
        />

        {(step.type === 'shell' || step.type === 'for_each_shell' || step.type === 'scale_916') && (
          <>
            <label className="node-field-label">Command</label>
            <div className="node-field-hint">Use {'{input}'}, {'{output}'}, {'{outputDir}'}, {'{basename}'}</div>
            <textarea
              className="node-field-textarea"
              value={step.command || def.defaultCommand || ''}
              onChange={e => onUpdate({ command: e.target.value })}
              rows={5}
            />
          </>
        )}

        {step.type === 'whisper' && (
          <>
            <label className="node-field-label">Model</label>
            <select className="node-field-select" value={step.model} onChange={e => onUpdate({ model: e.target.value })}>
              {['tiny','base','small','medium','large'].map(m => (
                <option key={m} value={m}>{m}</option>
              ))}
            </select>

            <label className="node-field-label">Output format</label>
            <select className="node-field-select" value={step.outputFormat} onChange={e => onUpdate({ outputFormat: e.target.value })}>
              {['srt','vtt','txt','json'].map(f => (
                <option key={f} value={f}>{f}</option>
              ))}
            </select>

            <label className="node-field-label">Words per line</label>
            <input
              className="node-field-input"
              type="number" min="1" max="20"
              value={step.wordsPerLine}
              onChange={e => onUpdate({ wordsPerLine: e.target.value })}
            />
          </>
        )}

        {step.type === 'ai_analyse' && (
          <>
            <label className="node-field-label">Prompt</label>
            <div className="node-field-hint">The AI will receive the content of the previous step's output file plus this prompt.</div>
            <textarea
              className="node-field-textarea"
              value={step.prompt}
              onChange={e => onUpdate({ prompt: e.target.value })}
              rows={8}
              placeholder="e.g. Read this transcript and return a JSON array of the best 3-5 clips for YouTube Shorts. Each item: {start, end, reason}. Return ONLY valid JSON."
            />
            <label className="node-field-label">Save output as</label>
            <select className="node-field-select" value={step.outputFormat} onChange={e => onUpdate({ outputFormat: e.target.value })}>
              <option value="json">JSON</option>
              <option value="txt">TXT</option>
            </select>
          </>
        )}

        {step.type === 'burn_captions' && (
          <>
            <label className="node-field-label">Font size</label>
            <input
              className="node-field-input"
              type="number" min="10" max="60"
              value={step.fontsize}
              onChange={e => onUpdate({ fontsize: e.target.value })}
            />
            <label className="node-field-label">Font color</label>
            <input
              className="node-field-input"
              value={step.fontcolor}
              onChange={e => onUpdate({ fontcolor: e.target.value })}
              placeholder="white, #FFFFFF, yellow..."
            />
            <div className="node-field-hint">
              Generated command: ffmpeg -y -i {'"{input}"'} -vf {"\"subtitles={srt}:force_style='FontSize={fontsize},PrimaryColour=&H{color}&'"} {'"{output}"'}
            </div>
          </>
        )}

        {step.type === 'ffmpeg_clip' && (
          <div className="node-field-hint" style={{ marginTop:12 }}>
            This step reads the JSON output from the previous AI Analyse step.
            Each item with start/end timestamps becomes one clip.
            The original input file is used as the source video.
          </div>
        )}

        <div className="node-type-desc">{def.description}</div>
      </div>
    </div>
  )
}

// ── Add step panel ────────────────────────────────────────────────────────────
function AddStepPanel({ onAdd }) {
  return (
    <div className="node-add-panel">
      <div className="node-editor-header">
        <span className="node-editor-header-title">Add Step</span>
      </div>
      <div className="node-add-list">
        {Object.entries(STEP_TYPES).map(([type, def]) => (
          <button
            key={type}
            className="node-add-type-btn"
            onClick={() => onAdd(type)}
            style={{ '--step-color': def.color }}
          >
            <span className="node-add-type-icon">{def.icon}</span>
            <div className="node-add-type-info">
              <div className="node-add-type-label">{def.label}</div>
              <div className="node-add-type-desc">{def.description}</div>
            </div>
          </button>
        ))}
      </div>
    </div>
  )
}

// ── Template modal ────────────────────────────────────────────────────────────
function TemplateModal({ onSelect, onClose }) {
  return (
    <div className="node-modal-backdrop" onClick={onClose}>
      <div className="node-modal" onClick={e => e.stopPropagation()}>
        <div className="node-modal-header">
          <span>Choose a template</span>
          <button className="node-modal-close" onClick={onClose}>×</button>
        </div>
        <div className="node-modal-grid">
          {TEMPLATES.map(t => (
            <button key={t.id} className="node-template-card" onClick={() => onSelect(t)}>
              <div className="node-template-icon">{t.icon}</div>
              <div className="node-template-name">{t.name}</div>
              <div className="node-template-desc">{t.description}</div>
              {t.steps.length > 0 && (
                <div className="node-template-steps">
                  {t.steps.map((s, i) => (
                    <span key={i} className="node-template-step-dot" style={{ background: stepColor(s.type) }} />
                  ))}
                </div>
              )}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

// ── Workflow compiler ─────────────────────────────────────────────────────────
// Converts pipeline JSON → the workflow object your existing runWorkflow IPC expects
export function buildWorkflow(pipeline, inputFile, project) {
  const outputDir = project
    ? `${project.folderPath}\\output`
    : 'output'
  const basename = inputFile.split(/[\\/]/).pop().replace(/\.[^.]+$/, '')

  const resolve = (str, extra = {}) =>
    (str || '')
      .replace(/\{input\}/g,     inputFile)
      .replace(/\{output\}/g,    `${outputDir}\\${basename}_step_${extra.stepNum ?? ''}.${extra.ext ?? 'mp4'}`)
      .replace(/\{outputDir\}/g, outputDir)
      .replace(/\{basename\}/g,  basename)
      .replace(/\{original\}/g,  inputFile)

  const steps = pipeline.steps.map((step, idx) => {
    const num = idx + 1
    const ext = step.outputFormat ?? 'mp4'

    if (step.type === 'shell' || step.type === 'for_each_shell' || step.type === 'scale_916') {
      return {
        id: num, type: 'shell',
        title: step.title,
        description: step.title,
        command: resolve(step.command || STEP_TYPES[step.type].defaultCommand, { stepNum: num, ext }),
        durationSec: null,
      }
    }

    if (step.type === 'whisper') {
      const cmd = `whisper "${inputFile}" --model ${step.model} --output_format ${step.outputFormat} --word_timestamps True --max_words_per_line ${step.wordsPerLine} --output_dir "${outputDir}"`
      return { id: num, type: 'shell', title: step.title, description: step.title, command: cmd, durationSec: null }
    }

    if (step.type === 'ai_analyse') {
      // Write a special shell step that will be intercepted by the pipeline runner
      return { id: num, type: 'ai_analyse', title: step.title, prompt: step.prompt, outputFormat: step.outputFormat }
    }

    if (step.type === 'ffmpeg_clip') {
      return { id: num, type: 'ffmpeg_clip', title: step.title, sourceVideo: inputFile }
    }

    if (step.type === 'burn_captions') {
      return {
        id: num, type: 'shell',
        title: step.title,
        command: `ffmpeg -y -i "${outputDir}\\clip_{n}.mp4" -vf "subtitles=${outputDir}\\clip_{n}.srt:force_style='FontSize=${step.fontsize},PrimaryColour=&Hffffff&'" "${outputDir}\\clip_{n}_captioned.mp4"`,
        durationSec: null,
      }
    }

    return { id: num, type: 'shell', title: step.title, command: '', durationSec: null }
  })

  return {
    message: pipeline.name,
    steps,
    final_output: `${outputDir}\\${basename}_final.mp4`,
  }
}
